on: [push]
name: mabl Tests
jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run mabl tests
        uses: mablhq/github-run-tests-action@v1
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: T4O4nIxujfGOWjpxaQA73A-a
          environment-id: S1zFp7RFx0F4phrmdapJ3Q-e
          continue-on-failure: 'true'